### ISSUE TITLE
libfastcommon的make.sh报错。

### ISSUE THREAD

**Issue by tangjinhui** [happyfish100/libfastcommon#20]
[root@localhost libfastcommon]# ./make.sh 
./make.sh:行158: 警告:立即文档在第 2 行被文件结束符分隔 (需要 `EOF')
./make.sh:行2: ./a.out: 没有那个文件或目录
./make.sh:行2: +: 未找到命令
nm: '/usr/lib/libc_r.so': No such file

**Comment by tangjinhui** [comment]
希望能给出一下建议谢谢

**Comment by happyfish100** [comment]
很奇怪的出错提示，请问你用的什么操作系统呢？

**Comment by tangjinhui** [comment]
centos7

**Comment by zhaop33** [comment]
这个有解决吗
