### ISSUE TITLE
您好在 5.17号 您更新了GIT后 编译 fastdfs 出现编译失败

### ISSUE THREAD

**Issue by clvspk** [happyfish100/libfastcommon#21]
![e_rckr zl7_ 3qdo72rg fe](https://user-images.githubusercontent.com/13034447/40212324-f86d015a-5a81-11e8-95bf-c86e937669fd.png)

使用之前的 libfastcommon 可以编译通过

**Comment by kongjun01** [comment]
同问，之前使用wiki操作都可以成功

**Comment by kongjun01** [comment]
tag：V.1.0.36可以使用

**Comment by azhou-iot** [comment]
我也是遇到跟kongjun01同样的情况

**Comment by happyfish100** [comment]
MacOS不支持安装到/usr/include，临时修改了Makefile.in，把目录修改为/usr/local/include。
然后不小心提交到github了。刚才已经把Makefile.in恢复了。
最新代码中没有这个问题了，我下次提交代码时注意。

**Comment by jiangyuantao** [comment]
最新检下来的代码还是有问题 提示这个
shared_func.h:204: 警告：提领类型双关的指针将破坏强重叠规则

**Comment by happyfish100** [comment]
已经修复了，感谢反馈！
