### ISSUE TITLE
libfastcommon编译不通过

### ISSUE THREAD

**Issue by hhlehh** [happyfish100/libfastcommon#39]
common_define.h文件中：
#define st_atimensec st_atim.tv_nsec
#define st_mtimensec st_mtim.tv_nsec
#define st_ctimensec st_ctim.tv_nsec
这几行内容编译时报错：error: expected ':', ',', ';', '}' or '__attribute__' before '.' token，这是什么原因呢，这些内容的作用是什么，注释掉有什么影响吗

**Comment by happyfish100** [comment]
你用的什么编译器及版本呢？

**Comment by SakuraLQY** [comment]
gcc -Wall -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -g -O1 -DDEBUG_FLAG -c -o ../common/fdfs_global.o ../common/fdfs_global.c  -I../common -I/usr/local/include
In file included from ../common/fdfs_global.c:21:0:
../common/fdfs_global.h:15:26: 致命错误：sf/sf_global.h：没有那个文件或目录
拉取最新的安装fastDfs不成功，少了很多文件

**Comment by happyfish100** [comment]
需要先编译和安装 libserverframe，v6.09新引入的网络框架库。
