### ISSUE TITLE
tracker_service.c, line: 1289，client ip addr: 客户端ip地址, operation not supported

### ISSUE THREAD

**Issue by ZHAIMZ** [happyfish100/libfastcommon#51]

**Comment by ZHAIMZ** [comment]
文件上传时自己写的文件上传 方法与tracker建立连接时报这个错误，请问如何解决？

**Comment by happyfish100** [comment]
服务器端配置了 IP 地址白名单吗？

**Comment by ZHAIMZ** [comment]
> 服务器端配置了 IP 地址白名单吗？

![c02ecb9375e6e617955a4e92dd64b08](https://github.com/user-attachments/assets/cc7d36af-a181-433c-b3aa-5f21267f54f3)
配置的全ip访问。
