### ISSUE TITLE
新版本编译出来缺少conn_pool_connect_server函数符号

### ISSUE THREAD

**Issue by jiehuliang** [happyfish100/libfastcommon#52]
![image](https://github.com/user-attachments/assets/af309e9c-f54f-48d2-bf92-e373202041cd)

**Comment by happyfish100** [comment]
使用最新版本的FastDFS 重新编译和安装就可以了。

**Comment by JCeYing** [comment]
使用最新版本的FastDFS和common最新代码，引用这两个编译出来的动态库编写代码，编译项目代码时，报错
/usr/include/fastcommon/fast_task_queue.h: In function ‘fast_task_info* free_queue_pop(fast_task_queue*)’:
/usr/include/fastcommon/fast_task_queue.h:208:36: error: invalid conversion from ‘void*’ to ‘fast_task_info*’ [-fpermissive]
     return fast_mblock_alloc_object(&queue->allocator);
希望您能解答一下

**Comment by jiehuliang** [comment]
> 使用最新版本的FastDFS和common最新代码，引用这两个编译出来的动态库编写代码，编译项目代码时，报错 /usr/include/fastcommon/fast_task_queue.h: In function ‘fast_task_info* free_queue_pop(fast_task_queue*)’: /usr/include/fastcommon/fast_task_queue.h:208:36: error: invalid conversion from ‘void*’ to ‘fast_task_info*’ [-fpermissive] return fast_mblock_alloc_object(&queue->allocator); 希望您能解答一下

隐式转换不成功，你可以在头文件fast_task_queue.h:208那里，返回值加一个显示转换。

**Comment by happyfish100** [comment]
你们用的是什么 C 编译器呢？应该不是 gcc 吧

**Comment by jiehuliang** [comment]
> 你们用的是什么 C 编译器呢？应该不是 gcc 吧

centos7.5，gcc4.8.5

**Comment by JCeYing** [comment]
> 你们用的是什么 C 编译器呢？应该不是 gcc 吧

gcc version 7.3.1 20180303 (Red Hat 7.3.1-5) (GCC)
centos7.9

**Comment by happyfish100** [comment]
照理说不应该报这样的错误，我按照你的建议改一下。
